### ISSUE TITLE
Dialog `closeOnOverlayClick` property does nothing

### ISSUE THREAD

**Issue by grahamscott** [BrandwatchLtd/axiom-react#1001]
The property is passed down to the underlying Modal component, but that component does nothing with it.

**Comment by lpoulter** [comment]
Ah good spot looks like I missed the name change in this PR
https://github.com/BrandwatchLtd/axiom-react/pull/963/files#diff-f7333c26a652814ef0d86363086deee90b3f502607af49c1c4930a1ea99719edL81

**Comment by lpoulter** [comment]
Fixed in `13.0.1`
