### ISSUE TITLE
@brandwatch/axiom-components are not compatible with next.js

### ISSUE THREAD

**Issue by SeaOfTea** [BrandwatchLtd/axiom-react#1017]
Due to the way that axiom-react imports global styles means that using axiom components in next.js is currently not possible. [Next.js explicitly disallows node_modules importing global styles](https://err.sh/next.js/css-npm). 
Obviously this is not a critical issue as I'm not aware of any brandwatch projects that are using next.js. However, I wonder if there is anything we could do that make this a possibility for the future.

Here is a codesandbox showing the issue: https://codesandbox.io/s/axiom-components-nextjs-issue-bor87

**Comment by lpoulter** [comment]
Thanks for raising this. I'm going to close for now as SSR is not on our roadmap.
