### ISSUE TITLE
Tick within the checkbox 

### ISSUE THREAD

**Issue by Flawwles** [BrandwatchLtd/axiom-react#874]
The tick within the checkbox looks a bit like a V right now - is there any small adjustments we can make to bring it back inline with the checkbox in the sketch file?

![tick-size](https://user-images.githubusercontent.com/7532495/81289793-e9ad5d80-905e-11ea-81d9-0c1387592378.jpg)

**Comment by lpoulter** [comment]
<img width="381" alt="Screenshot 2020-05-11 at 14 43 35" src="https://user-images.githubusercontent.com/3940567/81569003-8bea7f80-9396-11ea-8d13-0c9da79b1b7b.png">

**Comment by lpoulter** [comment]
Implemented in #886
