### ISSUE TITLE
Can we add more docs for validation

### ISSUE THREAD

**Issue by jdelight** [BrandwatchLtd/axiom-react#918]
Currently it looks like the docs are a little light on how to implement text input validation. A few more examples / code sandbox or within the docs would be good. Typical use cases would be (required, email pattern, and custom validation).

**Comment by lpoulter** [comment]
I've made this Pen for now. I'll write up some docs based around it https://codesandbox.io/s/zljzx99vyl?file=/src/index.js

**Comment by jdelight** [comment]
Great stuff - thanks @lpoulter would be good to potentially link out from the Axiom docs to examples like this but I don't know if we need to/should protect the examples somehow or if it's ok to have them public.

**Comment by lpoulter** [comment]
I definitely plan to add some code sandbox examples to the docs. I think the interactivity they bring makes a big difference.
