### ISSUE TITLE
Disabled checkbox styling is broken

### ISSUE THREAD

**Issue by Flawwles** [BrandwatchLtd/axiom-react#925]
A disabled checkbox has a subtle tick even if its not checked.
Its also not possible to tell if a disabled checkbox is enabled or disabled.

![image](https://user-images.githubusercontent.com/7532495/88191641-9301f980-cc33-11ea-85c1-0101fe064315.png)

This is something I noticed when selecting content sources and coudln't tell if it was checked and disabled or unchecked and disabled. 
![image](https://user-images.githubusercontent.com/7532495/88191897-d492a480-cc33-11ea-88d5-a242aabdf868.png)

**Comment by lpoulter** [comment]
Thanks for raising the issue. I have a fix but the tick is very faint for the disabled and checked scenario.

![2020-07-22 17 25 19](https://user-images.githubusercontent.com/3940567/88202268-8932c300-cc40-11ea-9a35-8ee37a294ff0.gif)

**Comment by Flawwles** [comment]
Can we style the tick to be grey when checked and disabled? 
![Checked-Disabled](https://user-images.githubusercontent.com/7532495/88266563-4cf67580-ccc7-11ea-93d3-99a784447925.png)
