### ISSUE TITLE
Documentation of Context component

### ISSUE THREAD

**Issue by andrewru** [BrandwatchLtd/axiom-react#970]
I'm implementing a tooltip that requires quite an amount of control over the style of its contents. It seems like this requires using the Position component and looking at the examples on that page it seems as if I ought to be using Context family components inside that. I've sort of figured out what I need to do by reading the source but I think it might be nice to have some documentation of the Context components and some (excuse the pun) context around what they are and how to use them to make it easier to understand, particularly as uses of the Position component are likely to be more complex and difficult to implement.

**Comment by lpoulter** [comment]
There is an indirect one line mention of Context [here](https://axiom.brandwatch.com/?path=/docs/dropdown--default-story#dropdowncontext). I agree we can do better.

**Comment by jdelight** [comment]
Thanks for raising @andrewru - totally agree - seems like there are a lot of components that use context under the hood so would be good to have some examples / docs on it.
