### ISSUE TITLE
Popper version / update

### ISSUE THREAD

**Issue by jdelight** [BrandwatchLtd/axiom-react#985]
Just wondering which version of Popper Axiom uses for Position and if it's possible to switch to the latest / react-popper implementation? I.e. do we need our own version of Position anymore? Probably one to discuss more broadly.

One reason is documentation but also it's been updated and it's not clear if we have access to the latest improvements. For example, I'm working on an announcement feature which needs the ability to put a padding around the context so it doesn't hit the edge of the browser window.

![image](https://user-images.githubusercontent.com/1387956/95269780-11813700-0832-11eb-97c6-784c85ddb505.png)

**Comment by lpoulter** [comment]
We are using [@popperjs/core": "^2.1.1](https://github.com/BrandwatchLtd/axiom-react/blob/master/packages/axiom-components/package.json#L20). I would guess we could update to @latest currently `2.5.3` without any problems. What Popper feature did you want to use? Position might need to be updated to pass a custom `modifiers` to `createPopper`.

**Comment by jdelight** [comment]
Hey @lpoulter - I was hoping to use the padding feature which prevents it from hitting the viewport edge (see top of the image above). I'm wondering if we can use react-popper as a replacement for our own react-popper wrapper. It's a bit of work but I think it worked quite nicely in Explore: https://github.com/BrandwatchLtd/explore-mode/blob/master/src/tooltips/Tooltips.js#L58

**Comment by lpoulter** [comment]
Ok i see we should be able to enable passing down of modifiers to the popper instance [padding](https://popper.js.org/docs/v2/modifiers/prevent-overflow/#padding) would go [here](https://github.com/BrandwatchLtd/axiom-react/blob/master/packages/axiom-components/src/Position/Position.js#L163) for instance. 

In terms of a rewrite to react popper I think It would make the Axiom code base a bit nicer but I'm not sure it's worth the development effort as we already have a working wrapper set-up. I don't think React popper has any features on top of popperjs/core.

**Comment by jdelight** [comment]
> I'm not sure it's worth the development effort as we already have a working wrapper set-up

I guess this is the bit I'd slightly disagree with :) simply because we've had to implement our own tooltips and work around Position a few times. So it works in some designed-for cases - but I'm less confident in using it anywhere because of hitting issues. I guess one approach would be having docs that show it's versatility - i.e. using Position with a canvas element or using other popper modifiers etc... both of which are valid use-cases. 

Another approach would be not having a wrapper so that devs can figure out those things from popper docs directly. So maybe something like "if Position doesn't work here's how to use React-Popper directly" for example. Less keen on that approach thought - feels messy.

The approach of adding popper props as and when they are needed seems less efficient to me. So another approach (probably my preferred) would be to "open up" `Position` so that it's a very thin wrapper and basically gives you access to all the underlying props / features. That way there's less of a rewrite needed, and it still works out the box for typical cases but also has support for more complex cases.

I guess we're trying to entrench some default positioning behaviour which is fine - but it can probably be done via default config.

**Comment by lpoulter** [comment]
>>> very thin wrapper and basically gives you access to all the underlying props / features
Yeah I agree with this was just less sure that Position needs to be changed to use React/Popper.

**Comment by lpoulter** [comment]
Here is a [quick implementation](https://github.com/BrandwatchLtd/axiom-react/pull/986) of passing modifiers to position.
